metadata:
  name: infinity
  type: cli
  language: go

targets:
- name: build/local
  stages:
  # - name: clone
  #   image: alpine:3.13
  #   commands:
  #   - apk add git
  #   - git clone https://github.com/JorritSalverda/infinity.git .
  - name: parallel
    stages:
    - name: lint
      image: golangci/golangci-lint:latest-alpine
      commands:
      - golangci-lint run
    - name: release
      image: golang:1.16-alpine
      env:
        CGO_ENABLED: 0
      commands:
      - go test -short ./...
      - go build -a -installsuffix cgo -o infinity .
  # - name: install
  #   runner: host
  #   commands:
  #   - go install
  - name: bake
    image: docker:20.10.7
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build -t jsalverda/infinity:latest .