type: cli
language: go
name: infinity

build:
  stages:
  - name: clone
    image: alpine:3.13
    commands:
    - apk add git
    - git clone https://github.com/JorritSalverda/infinity.git .
  - name: parallel
    stages:
    - name: lint
      image: golangci/golangci-lint:latest-alpine
      commands:
      - golangci-lint run
    - name: release
      image: golang:1.16-alpine
      env:
        CGO_ENABLED: 0
      commands:
      - go test -short ./...
      - go build -a -installsuffix cgo -o infinity .
      - ls -latr
  # - name: install
  #   runner: metal
  #   commands:
  #   - go install
  - name: bake
    image: docker:20.10.7-dind
    privileged: true
    commands:
    - ( dockerd-entrypoint.sh & )
    - ( while true ; do if [ -S /var/run/docker.sock ] ; then break ; fi ; sleep 3 ; done )
    - docker build -t jsalverda/infinity:latest .