metadata:
  name: hello-cmake
  type: firmware
  language: c++

targets:
- name: build/local
  stages:
  - name: build
    image: jsalverda/gcc-cmake:11.1.0
    commands:
    - cmake -version
    - cmake .
    - make
    - ./hello