build:
  stages:
  - name: upload
    bareMetal: true
    # image: jsalverda/arduino-cli:0.18.3
    # privileged: true
    # devices:
    # - /dev/cu.usbserial-1460:/dev/cu.usbserial-1460
    # shell: /bin/bash
    commands:
    - arduino-cli board list
    - arduino-cli core list
    - arduino-cli compile -b arduino:avr:uno sketches/blink
    - arduino-cli upload -b arduino:avr:uno -p /dev/cu.usbserial-1460 sketches/blink