metadata:
  name: hello-arduino
  type: firmware
  language: c++

build:
  stages:
  - name: upload-in-container
    image: jsalverda/arduino-cli:0.18.3
    privileged: true
    devices:
    - /dev/cu.usbserial-1460:/dev/cu.usbserial-1460
    commands:
    - arduino-cli board list
    - arduino-cli core list
    - arduino-cli compile -b arduino:avr:uno sketches/blink
    # - arduino-cli upload -b arduino:avr:uno -p /dev/cu.usbserial-1460 sketches/blink
  - name: upload-on-host
    runner: host
    commands:
    - arduino-cli version
    - arduino-cli core install arduino:avr
    - arduino-cli board list
    - arduino-cli core list
    - arduino-cli compile -b arduino:avr:uno sketches/blink
    - arduino-cli upload -b arduino:avr:uno -p /dev/cu.usbserial-1460 sketches/blink