version: 2.1

orbs:
  github-release: haskell-works/github-release@1.3.3

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  github_release:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build binaries
          environment:
            CGO_ENABLED: 0
          command: |
            GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X github.com/JorritSalverda/infinity/cmd.version=0.3.${CIRCLE_BUILD_NUM}" -o ./binaries/${CIRCLE_PROJECT_REPONAME}-v0.3.${CIRCLE_BUILD_NUM}-linux-amd64 .
            GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X github.com/JorritSalverda/infinity/cmd.version=0.3.${CIRCLE_BUILD_NUM}" -o ./binaries/${CIRCLE_PROJECT_REPONAME}-v0.3.${CIRCLE_BUILD_NUM}-windows-amd64.exe .
            GOOS=darwin GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X github.com/JorritSalverda/infinity/cmd.version=0.3.${CIRCLE_BUILD_NUM}" -o ./binaries/${CIRCLE_PROJECT_REPONAME}-v0.3.${CIRCLE_BUILD_NUM}-darwin-amd64 .
      - github/release:
          tag: v0.3.$CIRCLE_BUILD_NUM
          title: ${CIRCLE_PROJECT_REPONAME} v0.3.$CIRCLE_BUILD_NUM
          artefacts-folder: ./binaries/

workflows:
  build:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - github_release:
          requires:
            - hold
