type: web
language: node

build:
  stages:
  - name: audit
    image: node:16-alpine
    env:
      npm_config_update-notifier: false
    commands:
    - npm audit
  - name: restore
    image: node:16-alpine
    env:
      npm_config_update-notifier: false
    commands:
    - npm ci
  # - name: bake
  #   image: docker:20.10.7-dind
  #   privileged: true
  #   commands:
  #   - ( dockerd-entrypoint.sh & )
  #   - ( while true ; do if [ -S /var/run/docker.sock ] ; then break ; fi ; sleep 3 ; done )
  #   - docker build -t web:local .