metadata:
  name: error-cancels-parallel-stages
  type: cli
  language: go

build:
  stages:
  - name: parallel
    stages:
    - name: fails-in-container
      image: alpine:3.13
      commands:
      - sleep 1s
      - exit 1
    - name: gets-canceled-in-container
      image: alpine:3.13
      commands:
      - exec sleep 10s
    - name: gets-canceled-on-host
      runner: host
      commands:
      - sleep 10s